### ISSUE TITLE
Execute a stored procedure

### ISSUE THREAD

**Issue by relvar99** [metstrike/meteor-oracle#3]
Hello,

Without digging through the code, can this package execute an anonymous pl/sql procedure or a stored one?

begin
mystoredprocedure;
end;
/

or 

begin
 if .....
end if;
yadda-yadda
end;
/

Thanks,
Spencer

**Comment by metstrike** [comment]
Yes, it is possible on the server side only. Here is the working sample:

``` js
  var sql = "begin dbms_random.seed(:seed); :ret := dbms_random.random; end;";
  var params = {
    seed: 1234, 
    ret: {
        dir: NpmModuleOracledb.BIND_OUT, 
        type: NpmModuleOracledb.STRING, 
        maxSize: 50
    }
  };

  var db = OracleDB.getDatabase(Oracle._defaultOracleOptions);
  var result = db.executeCommand(sql, params);

  console.log(result.outBinds.ret);
```

The OracleDB class is exposed by the meteor-oracle package and you can refer to node-oracledb npm package through NpmModuleOracledb.

In order to make calls from the client side, the recommended secure way is to use Meteor.methods().
